EV_SUPPLY_REQUEST = "evSupplyRequest"       # Driver -> Central (solicitud de recarga)

EV_SUPPLY_AUTH_DRI = "evSupplyAuthDri"      # Central -> Driver (autorización) 
EV_SUPPLY_STARTED = "evSupplyStarted"       # Central -> Driver (Comienza el supply driver) 
EV_SUPPLY_TICKET = "evSupplyTicket"         # Central -> Driver (ticket final con precio)

EV_SUPPLY_CONNECTED = "evSupplyConnected" # Engine -> Central (Comienza el supply engine) 
EV_SUPPLY_AUTH = "evSupplyAuth" # Central -> Engine  (iniciar o rechazar)
EV_SUPPLY_END = "evSupplyEnd"   # Engine -> Central (fin del supply, trigger para que central mande el ticket)
EV_SUPPLY_HEARTBEAT = "evSupplyHeartbeat" # Engine -> Central (monitorizar estado)
EV_CENTRAL_HEARTBEAT = "evCentralHeartbeat" # Driver -> Central (latido para monitorizar estado)
EV_DRIVER_SUPPLY_HEARTBEAT = "evDriverSupplyHeartbeat" # Driver -> Central (monitorizar estado)
EV_DRIVER_SUPPLY_ERROR = "evDriverSupplyError" # Driver -> Central (error durante el suministro)
EV_SUPPLY_END_ENGINE = "evSupplyEndEngine" # Central -> Engine (fin del supply, trigger para que engine pare el suministro)
EV_ENGINE_KEY_EXCHANGE = "evEngineKeyExchange" # Central -> Engine (envío de clave para autenticación)